spring:
  # 数据库配置
  datasource:
    # 驱动
    driver-class-name:
    # 链接
    url:
    #用户名
    username:
    # 密码
    password:
application:
  config:
    # web域名或者ip+端口,携带协议
    web-domain:
    # 文件保存目录
    file-base: