spring:
  profiles:
    active: dev
  task:
    execution:
      thread-name-prefix: spring-thread-
  datasource:
    hikari:
      minimum-idle: 3
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
    type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: valid  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
server:
  servlet:
    context-path: /api
  tomcat:
    threads:
      min-spare: 5
