spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${db-url}
    username: ${db-username}
    password: ${db-password}
application:
  config:
    file-base: file